version: '3'

services:
    psql-db:
      image: 'postgres'
      container_name: psql-db
      environment:
        POSTGRES_USER: ${MY_FINANCES_DB_USERNAME}
        POSTGRES_PASSWORD: ${MY_FINANCES_DB_PASSWORD}
        POSTGRES_DB: MY_FINANCES
      volumes:
        - personal-finances-db:/var/lib/postgresql/data
    api:
      build: .
      environment:
        MY_FINANCES_DB_USERNAME: ${MY_FINANCES_DB_USERNAME}
        MY_FINANCES_DB_PASSWORD: ${MY_FINANCES_DB_PASSWORD}
        SPRING.PROFILES.ACTIVE: prod
      container_name: personal-finances-api
      ports:
        - "8080:8080"
      depends_on:
        - psql-db
    front-end:
      build: app
      container_name: personal-finances-front-end
      ports:
        - "3000:3000"

volumes:
  personal-finances-db:

